### ISSUE TITLE
Stop warning when no one is listening.

### ISSUE THREAD

**Issue by Towmeykaw** [MiguelSavignano/pub-sub-es6#1]
Hi! Really nice library. I had a small question, Is it possible to stop the logging when an event is fired and no one is listening? I have a timer event that fires every second but it only shows in one react component. So when that component is unmounted i get a warning every second.

**Comment by MiguelSavignano** [comment]
Thanks for the issue :)
I've implemented a function where you can set-up some debugger options.
If you check it, please, tell me what you think about it.
Thank you really much!

```javascript 
import PubSubEs6 from 'pub-sub-es6'
PubSubEs6.config.trace.not_found_subscriber = { exept: ["MY_LOOP_ACTION"] }
```

**Comment by Towmeykaw** [comment]
Works great. And i like the new logging. Very helpful for debugging.
